### GET - pobierz wszystkie surowe dane
GET http://localhost:3000/api/tags/raw HTTP/1.1

### GET - pobierz wszystkie dane
GET http://localhost:3000/api/tags HTTP/1.1

### GET - pobierz jeden element wg id
GET http://localhost:3000/api/tags/7 HTTP/1.1

### POST - nowe dane
POST http://localhost:3000/api/tags HTTP/1.1
content-type: application/json

{
    "name": "#nowytag",
    "popularity": 1000000
}

### PATCH - updatuj wg id
PATCH  http://localhost:3000/api/photos/tags/1684404207803 HTTP/1.1
content-type: application/json

{
    "name": "#nowytagdlazdjęcia",
    "popularity": 0
}

### PATCH - updatuj wg id
PATCH  http://localhost:3000/api/photos/tags/1685037309238 HTTP/1.1
content-type: application/json

[
    {
        "name": "#nowytag1",
        "popularity": 20
    },
    {
        "name": "#nowytag2",
        "popularity": 30
    },
    {
        "name": "#nowytag3",
        "popularity": 50
    }
]

### GET - pobierz tagi danego zdjęcia
GET  http://localhost:3000/api/photos/tags/1685037309238  HTTP/1.1

